- name: mongodb database playbook
  hosts: mongodb
  become: yes
  tasks:
  - name : copying mmongodb repo 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name : installing mongodb 
    ansible.builtin.package:
      name : mongodb-org
      state: present
  - name : start and enabling mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name : configuration change required 
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name : restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted
