- name: "app setup for application {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: "loading data into mongodb from {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-shell